# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"roman_to_int": "00_core.ipynb",
         "int_to_roman": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://sashafierce.github.io/hallo_nbdev/"

git_url = "https://github.com/sashafierce/hallo_nbdev/tree/master/"

def custom_doc_links(name): return None
